apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: calummoir-co-uk-tls
spec:
  secretName: calummoir-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: calummoir.co.uk
  dnsNames:
    - calummoir.co.uk
    - www.calummoir.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - calummoir.co.uk
          - www.calummoir.co.uk