apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'pgmoir@lft-concept.co.uk'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}